services:
  backend:
    build: .
    container_name: pytest-example
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: pytest-example-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
    