# Generated by Django 5.1.1 on 2024-09-19 04:01

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='order',
            trigger=pgtrigger.compiler.Trigger(name='read_only_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='da7163623a64614b247d55943a9e45429c9ee4b2', operation='UPDATE', pgid='pgtrigger_read_only_created_at_80a1a', table='order', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='order',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='UPDATE "order" SET is_active = False WHERE "id" = OLD."id"; RETURN NULL;', hash='6f7f1bbad00e7d3167219959189d38b83e5f7668', operation='DELETE', pgid='pgtrigger_soft_delete_78625', table='order', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='orderitem',
            trigger=pgtrigger.compiler.Trigger(name='update_total_price_on_item_change', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    BEGIN\n                        -- total_price를 갱신\n                        UPDATE "order" \n                        SET total_price = (\n                            SELECT COALESCE(SUM(p.price * oi.quantity), 0)\n                            FROM order_item oi\n                            JOIN product p ON oi.product_id = p.id\n                            WHERE oi.order_id = NEW.order_id\n                        )\n                        WHERE id = NEW.order_id;\n\n                        RETURN NEW;\n                    END;\n                    ', hash='d3276097d6f0177f1fed75049b784817884526d9', operation='INSERT OR DELETE OR UPDATE', pgid='pgtrigger_update_total_price_on_item_change_39ad0', table='order_item', when='BEFORE')),
        ),
    ]
